# Generated by Django 6.0.2 on 2026-02-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arangam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetailModel',
            new_name='UserDetail',
        ),
    ]
