# Generated by Django 6.0.2 on 2026-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arangam', '0002_rename_userdetailmodel_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='password',
            field=models.CharField(default='default123', max_length=255),
            preserve_default=False,
        ),
    ]
