# Generated by Django 6.0.2 on 2026-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arangam', '0003_userdetail_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='unique_id',
            field=models.CharField(default='arun16102505', max_length=100),
            preserve_default=False,
        ),
    ]
