# Generated by Django 6.0.2 on 2026-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arangam', '0004_userdetail_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
